### ISSUE TITLE
Inconsistent return for `with_check`

### ISSUE THREAD

**Issue by fanatid** [mycorrhiza/bs58-rs#43]
I'll write only about `decode`, but same relevant for `encode` too.

1) `new` and `with_alphabet` return new `DecodeBuilder`, but `with_check` instead change `DecodeBuilder` itself -- this looks inconsistent. For consistency `with_check` should return new `DecodeBuilder` or `with_alphabet` should change `DecodeBuilder` itself.

2) Does feature checks make any sense here? https://github.com/mycorrhiza/bs58-rs/blob/18cad1c914eb817cd90317b6c861b27f89123ac2/src/decode.rs#L178
It's not possible change `check` if feature disabled (except through unsafe), maybe:
```rust
    pub fn into<O: AsMut<[u8]>>(self, mut output: O) -> Result<usize> {
        #[cfg(feature = "check")]
        {
            if self.check {
                return decode_check_into(
                    self.input.as_ref(),
                    output.as_mut(),
                    self.alpha,
                    self.expected_ver,
                );
            }
        }

        decode_into(self.input.as_ref(), output.as_mut(), self.alpha)
    }
```

3) Does it makes sense define different structures for different features?
```rust
#[cfg(feature = "check")]
{
    #[allow(missing_debug_implementations)]
    pub struct DecodeBuilder<'a, I: AsRef<[u8]>> {
        input: I,
        alpha: &'a [u8; 58],
        check: bool,
        expected_ver: Option<u8>,
    }
}
#[cfg(not(feature = "check"))]
{
    #[allow(missing_debug_implementations)]
    pub struct DecodeBuilder<'a, I: AsRef<[u8]>> {
        input: I,
        alpha: &'a [u8; 58],
    }
}
```

Thanks.

**Comment by Nemo157** [comment]
1. The fact that `with_check` modifies `self` is not externally observable, the type signature of both it and `with_alphabet` is `fn(Self, new_value: _) -> Self`. It could be changed to use FRU syntax the same as `with_alphabet`.

2. Sounds like a fine change.

3. I believe this can be simplified to

```rust
#[allow(missing_debug_implementations)]
pub struct DecodeBuilder<'a, I: AsRef<[u8]>> {
    input: I,
    alpha: &'a [u8; 58],
    expected_ver: Option<u8>,
    #[cfg(feature = "check")]
    check: bool,
}
```

The problem would be that functions like `with_alphabet` else would also need to start adding `#[cfg(feature = "check")]` checks when they're updating the fields.

An alternative that might actually be nicer would be to use a custom enum, that would also allow inlining the `expected_ver` with the check value and get the compiler to check that it is used where necessary


```rust
enum Check {
    Disabled,
    #[cfg(feature = "check")]
    Enabled {
        expected_ver: u8,
    },
}

#[allow(missing_debug_implementations)]
pub struct DecodeBuilder<'a, I: AsRef<[u8]>> {
    input: I,
    alpha: &'a [u8; 58],
    check: Check,
}
```

**Comment by fanatid** [comment]
1. Are you ok with changes for using FRU syntax?
2. Changes submitted.
3. My initial thoughts was reduce size required for structure.
`expected_ver: Option<u8>` -- 2 bytes, `check: bool` -- 1 byte
Proposed enum is 2 bytes, so probably such changes does not worth a lot.

**Comment by Nemo157** [comment]
Yep, changing the method to FRU would probably make it better IMO.

Currently `expected_ver` + `check` will be taking 3 bytes, the `Check` enum will be 2 bytes with `feature = "check"` and 0 bytes without it, so it is a size win.

**Comment by Nemo157** [comment]
More importantly, changing to use a custom enum with `#[cfg]`ed out variants would provide compile-time checking that the correct variants are handled (instead of having the `unreachable!` in the old code, or having a potential fallthrough with #44).

**Comment by fanatid** [comment]
Oh, you're right about 0 bytes in case when `feature = "check"` disabled. I think this should be preferred way compare to #44, so I'll close that PR.

**Comment by fanatid** [comment]
Will submit item 1 shortly

**Comment by fanatid** [comment]
There yet one thing about which I wanted ask.
Right now for decode/encode data with not default alphabet and enabled checksum syntax is:
```rust
decode::DecodeBuilder::new(data, alphabet::RIPPLE).with_check(Some(110)).into(output)
```
It's looks strange that for builder we need data and only then alphabet / check. While usual way is  define alphabet and/or check and then process data.
I'd propose change API to something like:
```rust
enum Check {
    Disabled,
    #[cfg(feature = "check")]
    Enabled(Option<u8>),
}

struct DecodeBuilder {
    zero: u8,
    alpha: [u8; 128],
    check: Check,
}

impl DecodeBuilder {
    pub fn new() -> DecodeBuilder {
        DecodeBuilder {
            zero: 0,
            alpha: [0; 128],
            check: Check::Disabled,
        }
    }

    pub fn with_alphabet(self, base: &[u8; 58]) -> DecodeBuilder {
        let mut alpha = [0xFF; 128];
        for (i, &c) in base.iter().enumerate() {
            alpha[c as usize] = i as u8;
        }
        DecodeBuilder { zero: base[0], alpha, ..self }
    }

    #[cfg(feature = "check")]
    #[cfg_attr(docsrs, doc(cfg(feature = "check")))]
    pub fn with_check(self, expected_ver: Option<u8>) -> DecodeBuilder {
        self.check = Check::Enabled(expected_ver);
        DecodeBuilder { check, ..self }
    }

    pub fn create<I: AsRef<[u8]>>(&self, input: I) -> Decode<'_, I> {
        Decode { inner: self, input }
    }
}

struct Decode<'a, I: AsRef<[u8]>> {
    inner: &'a DecodeBuilder,
    input: I,
}

impl<'a, I: AsRef<[u8]>> Decode<'a, I> {
    #[cfg(feature = "alloc")]
    #[cfg_attr(docsrs, doc(cfg(any(feature = "alloc", feature = "std"))))]
    pub fn into_vec(self) -> Result<Vec<u8>>;

    pub fn into<O: AsMut<[u8]>>(self, mut output: O) -> Result<usize>;
}
```

With this it will be possible create object which will have alphabet / check and then decode data with defined options. If we also will transform alphabet in builder performance will be improved:
```
empty/decode_bs58       time:   [25.264 ns 25.566 ns 25.939 ns]                               
                        change: [-35.939% -34.962% -33.875%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
  2 (2.00%) high mild
  13 (13.00%) high severe

1_byte/decode_bs58      time:   [67.183 ns 68.250 ns 69.595 ns]                               
                        change: [-26.859% -24.031% -21.798%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  1 (1.00%) high mild
  12 (12.00%) high severe

5_bytes/decode_bs58     time:   [86.053 ns 87.024 ns 88.221 ns]                                
                        change: [-19.471% -18.022% -16.408%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 13 outliers among 100 measurements (13.00%)
  2 (2.00%) high mild
  11 (11.00%) high severe

10_bytes/decode_bs58    time:   [123.39 ns 124.90 ns 126.72 ns]                                 
                        change: [-15.409% -14.204% -13.010%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 12 outliers among 100 measurements (12.00%)
  5 (5.00%) high mild
  7 (7.00%) high severe

10_bytes_zero/decode_bs58                                                                            
                        time:   [83.625 ns 84.685 ns 85.955 ns]
                        change: [-22.269% -20.879% -19.502%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 18 outliers among 100 measurements (18.00%)
  4 (4.00%) high mild
  14 (14.00%) high severe

10_bytes_max/decode_bs58                                                                            
                        time:   [123.63 ns 125.20 ns 127.13 ns]
                        change: [-15.405% -14.042% -12.561%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
  7 (7.00%) high mild
  8 (8.00%) high severe

32_bytes/decode_bs58    time:   [500.70 ns 506.45 ns 513.69 ns]                                  
                        change: [-3.6403% -2.1763% -0.7385%] (p = 0.00 < 0.05)
                        Change within noise threshold.
Found 15 outliers among 100 measurements (15.00%)
  5 (5.00%) high mild
  10 (10.00%) high severe

256_bytes/decode_bs58   time:   [31.169 us 31.536 us 31.990 us]                                   
                        change: [-0.8981% +0.4257% +1.8426%] (p = 0.55 > 0.05)
                        No change in performance detected.
Found 12 outliers among 100 measurements (12.00%)
  12 (12.00%) high severe
```

**Comment by Nemo157** [comment]
The primary intended API is like

```rust
decode(data).with_alphabet(alphabet::RIPPLE).with_check(Some(110)).into(output)
```

not going through the `DecodeBuilder::new` constructor (I'd be tempted to deprecate the constructor, not sure why I really added it).

One idea to avoid any breaking API changes is to allow providing a "prepared alphabet" as well as the current bytes. Something like

```
struct Alphabet {
    encode: [u8; 58],
    decode: [u8; 256],
}

impl Alphabet {
    pub const fn new(base: &[u8; 58]) -> Alphabet { ... }
}

struct DecodeBuilder<'a> {
    alpha: Cow<'a, Alphabet>,
    check: Check,
}

impl DecodeBuilder {
    pub fn with_alphabet(self, alpha: &[u8; 58]) -> DecodeBuilder {
        DecodeBuilder { alpha: Cow::Owned(Alphabet::from(alpha)), ..self }
    }

    pub fn with_prepared_alphabet(self, alpha: &Alphabet) -> DecodeBuilder {
        DecodeBuilder { alpha: Cow::Borrowed(alpha), ..self }
    }
}
```

Along with `static`s containing the `Alphabet` for the known set. That allows avoiding any copying of bytes when using a prepared alphabet, without having to store the `DecodeBuilder` anywhere.

(And then a future breaking version could drop `with_alphabet` and change the `Cow<'a, Alphabet>` into a simple `&'a Alphabet`).

**Comment by fanatid** [comment]
Looks good for performance improvement, 2 notes:
- `const fn` -- right now in nightly (if I understand correctly) + `new` function require `assert!(base.iter().all(|&c| c < 128));` which contain `if` and can not be used with `const fn`...
```bash
error[E0658]: `if` is not allowed in a `const fn`
  --> src/alphabet.rs:34:9
   |
34 |         assert!(base.iter().all(|&c| c < 128));
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #49146 <https://github.com/rust-lang/rust/issues/49146> for more information
   = help: add `#![feature(const_if_match)]` to the crate attributes to enable
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

- `Cow` in `std`, but `std` can be feature and `Cow` will not be available

**Comment by fanatid** [comment]
local enum.. i.e. something like:
```rust
enum AlphabetCow<'a> {
    Borrowed(&'a Alphabet),
    Owned(Alphabet),
}
```

?

**Comment by Nemo157** [comment]
Yep.

**Comment by fanatid** [comment]
Before close this issue, I'd like ask about idea in #47 -- is this something what cost of time work on? Is this useful thing which can be accepted?

**Comment by Nemo157** [comment]
Yep, I think it makes sense to handle. I've left a couple comments of small changes that should get it working.

**Comment by fanatid** [comment]
Anything with what I can help for new release? Do you want make breaking change release?

**Comment by Nemo157** [comment]
I'll publish a release later today, at the moment I don't think there's much need for a breaking release.
